### PR TITLE
Switch to GitHub actions

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This is an early draft as some stuff needs fixing. It will depend on something like #137 and #138 landing.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
I'll rebase this now and see how it goes.

**Comment by bvssvni** [comment]
@jhasse Do you have access to disable Appveyor for this repo? We no longer need it since we are transitioning to Github actions.

**Comment by bvssvni** [comment]
Merging.

**Comment by bvssvni** [comment]
Thanks!

**Pull request merged**
