### PR TITLE
Add missing libpng and libz for rendering bitmap glyphs

### LINKED ISSUE #133: Freetype doesnt load bitmap emojis
when trying to load noto emoji fonts, it works on desktop but not android. More specifically `FT_Load_Glyph` will return `FT_Err_Unimplemented_Feature`.

I thought maybe this was due to lacking PNG support in the bundled version, so on my local copy I've uncommented `#define FT_CONFIG_OPTION_USE_PNG` in `freetype2/include/freetype/config/ftoption.h` and then add `libpng-sys = { git = "https://github.com/kornelski/rust-libpng-sys", features = ["static-libz", "static" ] }` to my `Cargo.toml`. But this hasn't fixed it.

Any ideas what's missing?

### PR DESCRIPTION
**Pull request by narodnik**
Fixes #133

### CODE REVIEW

**Comment by bvssvni** [comment]
@narodnik Can you rebase?

**Comment by narodnik** [comment]
ok I found it easier to redo the entire commit. Plz pull it now so I don't have to do this all over again

**Comment by bvssvni** [comment]
@narodnik some of the checks are failing.

**Comment by narodnik** [comment]
The windows build works but is failing during the test because it isn't recursively checking out the submodule properly.

`libz-sys` contains a submodule in `src/zlib` to another submodule for `zlib`, which includes the `zlib.h`:

```rust
    build.include("libpng").include("libz-sys/src/zlib");
```

So this is an error with the CI build system, rather than the code.

**Comment by bvssvni** [comment]
Merging.

**Comment by bvssvni** [comment]
Thanks!

**Pull request merged**
