### PR TITLE
Linking with Msys2

### PR DESCRIPTION
**Pull request by DenisKolodin**
Another way to get dependencies in Windows

### CODE REVIEW

**Comment by tomaka** [comment]
The right method is the Cargo build script, not exporting `LD_LIBRARY_PATH`.

**Comment by kryptan** [comment]
The name of the library in MSYS2 is libfreetype.dll.a while this crate always tries to link to libfreetype-6.a. I created an issue for this #38.

**Comment by retep998** [comment]
Theoretically the build script uses pkgconfig, so if you're using msys2, it should automatically figure out what the library is actually named.

**Comment by bvssvni** [comment]
Closing because the recommended method is to use Cargo build script.

**Pull request closed without merging**
