### PR TITLE
Vendor freetype 2.6.3 (fixes #50)

### LINKED ISSUE #50: Build freetype in build script
As title. See https://github.com/Eljay/assimp-sys for an example of how it can be done (essentially he's keeping the actual library as a submodule and then just building it with cmake-rs in the build.rs script).

Doing it that way, you can (as a user of this library) get started without installing freetype first, as it will be built as part of the cargo build. Or if you have a local install you can also take advantage of that.

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by jhasse** [comment]
To fix Windows build: Is it possible to fallback to linking freetype as before when `make` isn't found?

**Comment by nox** [comment]
@jhasse It just uses cmake now, per @tomaka's suggestion.

**Comment by nox** [comment]
@jhasse See also, https://github.com/PistonDevelopers/freetype-sys/issues/63.

**Comment by nox** [comment]
Given that vendors Freetype, we should probably include its license somewhere.

**Comment by jhasse** [comment]
It seems that you've added all the freetypes source files. Can you do that by only adding the source tarball or adding `http://git.savannah.gnu.org/cgit/freetype/freetype2.git/` as a submodule? That makes it easier to update FreeType in the future and als one can easily verify all the files by checking the SHA hash.

The submodule would also have the added bonus that it's possible to git-bisect bugs in FreeTypes source.

**Comment by nox** [comment]
@jhasse I'm -1 on submodules, given that Cargo doesn't know what to do with them at all.

**Comment by jhasse** [comment]
So cargo doesn't clone recursively when adding a git repo by hand?

**Comment by nox** [comment]
I believe we should do a freetype-src crate instead, like sqlite3-sys and sqlite3-src.

**Pull request closed without merging**
