### PR TITLE
Add feature nopkgcfg

### LINKED ISSUE #14: Add a feature/environment variable to opt-out of pkg-config
On OSX, I have problem where pkg-config looks up a version of FreeType belonging to the Mono framework, which is built for another target platform. To fix this, I have to override "freetype-sys" through Cargo and change the main method of build.rs into:

```Rust
fn main() {
    println!("cargo:rustc-flags=-l freetype:dylib");
    /*
    match pkg_config::find_library("freetype2") {
        Ok(_) => return,
        Err(_) => {
            if cfg!(windows) {
                println!("cargo:rustc-flags=-l freetype-6:dylib");
            } else {
                println!("cargo:rustc-flags=-l freetype:dylib");
            }
        }
    }
    */
}
```

It would be nice if there was a feature/environment variable to disable pkg-config.

### PR DESCRIPTION
**Pull request by Potpourri**
close #14

### CODE REVIEW

**Comment by tomaka** [comment]
That's a very bad design >_>

**Comment by Potpourri** [comment]
I'm sorry, I did not know it was so bad.
How do I fix it, revert?

**Comment by bvssvni** [comment]
Reverted.

**Comment by tomaka** [comment]
> I'm sorry, I did not know it was so bad.

Don't worry.

The problem with that design is that you choose which Cargo features are enabled/disabled when you use the package as a dependency. But the choice whether to use pkg-config to find freetype is platform-dependant or user-dependant.

If you want to use the package A which depends on freetype-sys, it's the author of package A that decides whether `nopkgcfg` is enabled, not you.

**Pull request merged**
