### PR TITLE
Fix build script

### PR DESCRIPTION
**Pull request by Potpourri**

### CODE REVIEW

**Comment by tomaka** [comment]
Why? Hyphens are still allowed, the difference is that you can write `extern crate freetype_sys;` now.

**Comment by Potpourri** [comment]
Cargo not allowed hypens in target name.
`target names cannot contain hyphens:`
I change package name just to consistent with crate name. I can change only target name, if you want.

**Comment by bvssvni** [comment]
@Potpourri Don't change package name, since that's the name on crates.io we are using.

**Comment by Potpourri** [comment]
Ok.

**Comment by Potpourri** [comment]
Why then sdl2-sys changed to sdl2_sys?

**Comment by bvssvni** [comment]
@Potpourri That's because I did a mistake. Thanks for catching this! https://github.com/AngryLawyer/rust-sdl2/pull/365#issuecomment-86197031

**Comment by Potpourri** [comment]
@tomaka, @bvssvni now is ok?

**Comment by tomaka** [comment]
There's nothing to change, where do you see `target names cannot contain hyphens:`?

`alsa-sys`; `user32-sys`, etc. all work for me.

**Comment by bvssvni** [comment]
It seems to work on `rustc 1.0.0-nightly (123a754cb 2015-03-24) (built 2015-03-25)`.

**Comment by Potpourri** [comment]
Yeah, I got it. Latest cargo `cargo 0.0.1-pre-nightly (0e42b4d 2015-03-25) (built 2015-03-25)`
not allowed hyphens in target name, but if target name not set, then cargo automate set name from package name with change hyphens to underscore.

**Comment by tomaka** [comment]
Cargo doesn't change anything, it's just that `a-b` and `a_b` are interchangeable.
That means that for example in the `[dependencies]` section, you can write either `foo-bar` or `foo_bar`, and both will refer to the same crate.

**Comment by Potpourri** [comment]
Cargo set crate name for freetype-sys as `rustc src/lib.rs --crate-name freetype_sys`. Previously, package name = crate name. Now no.

**Comment by bvssvni** [comment]
Looks good! Thanks!

**Pull request merged**
