### PR TITLE
Remove `cmake` dependency and upgrade to Freetype 2.12.1

### PR DESCRIPTION
**Pull request by Jasper-Bekkers**
This PR addresses two things with `freetype-sys`, it removes `cmake` in favor of just building the code with `cc`. This simplifies the developer setup (we at Traverse-Research have a hard policy against having cmake in our buildtree).

At the same time I took the liberty to update to the last freetype release.

### CODE REVIEW

**Comment by Jasper-Bekkers** [comment]
Because of the freetype upgrade this changes a huge amount of file, the bulk of the actual work is in [21b56f2](https://github.com/PistonDevelopers/freetype-sys/pull/106/commits/21b56f23680d2bc5b37d69469cb81bbb58278b95)

**Comment by bvssvni** [comment]
Merging

**Comment by bvssvni** [comment]
Thanks!

**Comment by Jasper-Bekkers** [comment]
Thanks! Could you spin a new release with this in it?

**Pull request merged**
